{% set name = "sweets" %}
{% set version = "0.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/isce-framework/sweets/archive/v{{ version }}.tar.gz
  sha256: 4cfddd24230878d5c73c031f09f5c95e7f12dcba640d1354a92d3b12c6404aec

build:
  entry_points:
    - sweets = sweets.cli:main
  noarch: python
  script:
    - export SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}
    - {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=64.0
    - setuptools-scm >=6.2
    - pip >=21.3
  run:
    - python >=3.8
    - wget # ASF Downloading
    - compass >=0.4.1
    - dask
    - dolphin >=0.3.0
    - gdal
    - h5py
    - hdf5 !=1.12.2 # https://github.com/SciTools/iris/issues/5187 and https://github.com/pydata/xarray/issues/7549
    - numpy
    - pydantic >=2.1
    - pyproj >=3.3
    - pyre >=1.12.1
    - python-dateutil
    - rasterio
    - requests
    - rich
    - rioxarray
    - sardem
    - sentineleof
    - shapely

test:
  imports:
    - sweets
    - sweets.core
  commands:
    - sweets --help
  requires:
    - pip

about:
  home: https://github.com/isce-framework/sweets
  summary: Workflows for generating surface displacement maps using InSAR
  license: BSD-3-Clause OR Apache-2.0
  license_file: LICENSE
  dev_url: https://github.com/isce-framework/sweets

extra:
  recipe-maintainers:
    - scottstanie
